### ISSUE TITLE
Investigate if the relayer incorrectly marks a message as processed when the processing reverts

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/abacus-monorepo#573]
It's possible for a relayer's `InboxValidatorManager.process` transaction to revert if the message's handler reverts. This usually happens in a situation where gas estimation is successful but between the time of gas estimation and when the tx is included in a block, a state change has occurred that results in the transaction reverting. This case is tested on `testnet2` with kathy sending messages to TestSendReceiver, which will revert if the previous block's hash is odd ([see here](https://github.com/abacus-network/abacus-monorepo/blob/main/solidity/core/contracts/test/TestSendReceiver.sol#L49)). It seems like the relayer doesn't try to submit the process tx again, but it should. We should confirm if this is the case and understand why. It's likely that the relayer only cares if the transaction has been included in a block, but doesn't check if the transaction reverted or not.

**Comment by nambrot** [comment]
https://github.com/abacus-network/abacus-monorepo/blob/d120a76c1ebe84d184a918fa95e5a5b61bfe4a41/rust/abacus-core/src/traits/mod.rs#L38 indeed just checks that the tx was included.
